orbs:
  win: circleci/windows@2.4.0

executors:
  linux:
    docker:
      - image: circleci/node:12-browsers
  mac:
    macos:
      xcode: "11.3.1"

commands:
  install-deps:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: Install deps
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
  run-test:
    steps:
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run test
          command: npm run test
      - store_artifacts:
          path: ./tmp

version: 2.1
jobs:
  test-linux:
    executor: linux
    steps:
      - checkout
      - install-deps
      - run-test
  test-mac:
    executor: mac
    steps:
      - checkout
      - install-deps
      - run-test
  test-windows:
    executor: win/default
    steps:
      - checkout
      - install-deps
      - run-test
  release:
    executor: linux
    steps:
      - checkout
      - install-deps
      - run:
          name: "パッケージをビルドする"
          command: npm build
      - run:
          name: "npmトークンを設定する"
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: "npmパッケージとして公開する"
          command: npm publish
workflows:
  version: 2
  test:
    jobs:
      - test-linux:
          context: OSS
      - test-mac:
          context: OSS
      - test-windows:
          context: OSS
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
