orbs:
  win: circleci/windows@2.4.0
  npm-publisher: uraway/npm-publisher@0.1.0

executors:
  linux:
    docker:
      - image: circleci/node:12-browsers
  mac:
    macos:
      xcode: "11.3.1"

commands:
  install-deps:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: Install deps
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
  run-test:
    steps:
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run test
          command: npm run test
      - store_artifacts:
          path: ./tmp

version: 2.1
jobs:
  lint:
    executor: linux
    steps:
      - checkout
      - install-deps
      - run: npm run eslint
  test-linux:
    executor: linux
    steps:
      - checkout
      - install-deps
      - run-test
  test-mac:
    executor: mac
    steps:
      - checkout
      - install-deps
      - run-test
  test-windows:
    executor: win/default
    steps:
      - checkout
      - install-deps
      - run-test

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test-linux:
          context: OSS
      - test-windows:
          context: OSS
      - npm-publisher/publish-from-package-version:
          requires:
            - test-linux
            - test-windows
          filters:
            branches:
              only: master
          context: OSS
          name: publish-npm-package
          publish-token-variable: NPM_TOKEN
          push-git-tag: true
          ssh-fingerprints: 14:7a:e7:17:8b:dd:ff:5c:8c:11:cf:ed:e0:a5:e6:fc
          pre-publish-steps:
            - checkout
            - install-deps
            - run:
                name: "パッケージをビルドする"
                command: npm run build
